import Foundation

/// Generates a human-readable Markdown model card next to a checkpoint —
/// architecture, dataset/training context, metrics, and known limitations.
enum ModelCard {
    static func generate(meta: Checkpoint.Meta, hardware: HardwareInfo, datasetName: String?, method: String) -> String {
        let df = DateFormatter(); df.dateStyle = .medium; df.timeStyle = .short
        var s = String(localized: "model-card.header.title", defaultValue: "# Model Card", comment: "Markdown header for model card title") + "\n\n"
        s += String(format: String(localized: "model-card.header.generated-date", defaultValue: "Generated by LabLLM on %@.", comment: "Sentence in model card header showing generation timestamp"), df.string(from: meta.createdAt)) + "\n\n"

        s += String(localized: "model-card.section.architecture", defaultValue: "## Architecture", comment: "Markdown section header for architecture details") + "\n"
        s += String(localized: "model-card.architecture.type", defaultValue: "- Type: GPT-style decoder-only transformer", comment: "Architecture bullet describing model type") + "\n"
        s += String(format: String(localized: "model-card.architecture.layers", defaultValue: "- Layers: %d", comment: "Architecture bullet showing transformer layer count"), meta.config.nLayers) + "\n"
        s += String(format: String(localized: "model-card.architecture.hidden-dimension", defaultValue: "- Hidden dimension: %d", comment: "Architecture bullet showing hidden embedding dimension"), meta.config.nEmbd) + "\n"
        s += String(format: String(localized: "model-card.architecture.attention-heads", defaultValue: "- Attention heads: %d", comment: "Architecture bullet showing number of attention heads"), meta.config.nHeads) + "\n"
        s += String(format: String(localized: "model-card.architecture.context-length", defaultValue: "- Context length: %d", comment: "Architecture bullet showing model context length"), meta.config.blockSize) + "\n"
        s += String(format: String(localized: "model-card.architecture.mlp-ratio", defaultValue: "- MLP ratio: %@", comment: "Architecture bullet showing MLP expansion ratio"), String(describing: meta.config.mlpRatio)) + "\n"
        s += String(format: String(localized: "model-card.architecture.weight-tying", defaultValue: "- Weight tying: %@", comment: "Architecture bullet indicating whether embedding weights are tied"), meta.config.tieWeights ? String(localized: "model-card.boolean.yes", defaultValue: "yes", comment: "Boolean yes label used in model card output") : String(localized: "model-card.boolean.no", defaultValue: "no", comment: "Boolean no label used in model card output")) + "\n"
        s += String(format: String(localized: "model-card.architecture.parameters-approx", defaultValue: "- Parameters (approx.): %@", comment: "Architecture bullet showing approximate parameter count"), format(meta.config.estimatedParameters)) + "\n\n"

        s += String(localized: "model-card.section.tokenizer", defaultValue: "## Tokenizer", comment: "Markdown section header for tokenizer details") + "\n"
        s += String(format: String(localized: "model-card.tokenizer.kind", defaultValue: "- Kind: %@", comment: "Tokenizer bullet showing tokenizer kind label"), meta.tokenizer.kind.label) + "\n"
        s += String(format: String(localized: "model-card.tokenizer.vocabulary-size", defaultValue: "- Vocabulary size: %d", comment: "Tokenizer bullet showing vocabulary size"), meta.tokenizer.vocabSize) + "\n\n"

        s += String(localized: "model-card.section.training", defaultValue: "## Training", comment: "Markdown section header for training details") + "\n"
        s += String(format: String(localized: "model-card.training.method", defaultValue: "- Method: %@", comment: "Training bullet showing training method name"), method) + "\n"
        s += String(format: String(localized: "model-card.training.steps-completed", defaultValue: "- Steps completed: %d", comment: "Training bullet showing completed step count"), meta.step) + "\n"
        s += String(format: String(localized: "model-card.training.final-train-loss", defaultValue: "- Final train loss: %.4f", comment: "Training bullet showing final training loss value"), meta.loss) + "\n"
        if meta.valLoss > 0 { s += String(format: String(localized: "model-card.training.final-val-loss", defaultValue: "- Final val loss: %.4f", comment: "Training bullet showing final validation loss value"), meta.valLoss) + "\n" }
        if let d = datasetName { s += String(format: String(localized: "model-card.training.dataset", defaultValue: "- Dataset: %@", comment: "Training bullet showing dataset name"), d) + "\n" }
        s += "\n"

        s += String(localized: "model-card.section.hardware", defaultValue: "## Hardware", comment: "Markdown section header for hardware details") + "\n"
        s += String(format: String(localized: "model-card.hardware.trained-on", defaultValue: "- Trained on: %@", comment: "Hardware bullet showing training chip"), hardware.chip) + "\n"
        s += String(format: String(localized: "model-card.hardware.unified-memory-gb", defaultValue: "- Unified memory: %.0f GB", comment: "Hardware bullet showing unified memory in gigabytes"), hardware.physicalMemoryGB) + "\n\n"

        s += String(localized: "model-card.section.limitations", defaultValue: "## Limitations", comment: "Markdown section header for model limitations") + "\n"
        s += String(localized: "model-card.limitations.local-demo-not-production", defaultValue: "- Small local model trained for demonstration/learning purposes, not production use.", comment: "Limitation bullet indicating model is for learning and not production") + "\n"
        s += String(localized: "model-card.limitations.output-quality", defaultValue: "- May produce inaccurate, repetitive, or nonsensical output, especially outside its training distribution.", comment: "Limitation bullet about potential low-quality outputs") + "\n"
        s += String(localized: "model-card.limitations.not-evaluated-safety-bias-factual", defaultValue: "- Not evaluated for safety, bias, or factual reliability.", comment: "Limitation bullet about missing safety and reliability evaluation") + "\n\n"

        s += String(localized: "model-card.section.intended-use", defaultValue: "## Intended use", comment: "Markdown section header for intended use") + "\n"
        s += String(localized: "model-card.intended-use.local-experimentation-only", defaultValue: "Local experimentation and learning about how small language models are trained. Not intended for deployment.", comment: "Intended-use statement restricting model to local experimentation and learning") + "\n"
        return s
    }

    private static func format(_ n: Int) -> String {
        let f = NumberFormatter(); f.numberStyle = .decimal
        return f.string(from: NSNumber(value: n)) ?? "\(n)"
    }
}
